config/routes.rb
Rails.application.routes.draw do
  resources :categories
  post 'sign_in' => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'
  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  get 'ad/new' => 'advertisements#new'
  get 'ad/list' => 'advertisements#list'
  get 'message/list' => 'messages#list_messages'
  get 'email_box' => 'chats#email_box'
  post 'ad/index' => 'advertisements#index'
  get 'ad/index' => 'advertisements#index'

  root 'welcome#index'
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :travelers, only: [:new, :create, :show, :edit, :update]
  resources :advertisements, only: [:new, :create, :show, :edit, :update]
  resources :messages, only: [:new, :create]
  resources :chats, only: [:show]

end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  has_one :category
  belongs_to :traveler
  has_many :chats
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :set_advertisement, only: [:show, :edit, :update, :destroy]
  before_action :redirect_if_traveler, only: [:new,:edit, :update, :destroy]

  def new
    @advertisement = Advertisement.new
    @category = Category.new
  end

  def index
    if params[:search]
      @results = Advertisement.find_by_type_itens(:search)
    else
      @results = Advertisement.all
    end
  end

  def show
    puts "-" * 30
    puts "-" * 30
    puts params[:qualification]
    puts "-" * 30
    puts "-" * 30
  end

  def edit
  end

  def create
    @advertisement = Advertisement.new(advertisement_params)
    @advertisement.traveler_id = current_user.id

      if @advertisement.save
        redirect_to @advertisement
      else
        render 'new'
      end
  end

  def update
      if @advertisement.update(advertisement_params)
        redirect_to @advertisement
      else
        render 'edit'
      end
  end

  def list
    @advertisements = Advertisement.all
  end

   private

   def set_advertisement
    @advertisement = Advertisement.find(params[:id])
   end

   def advertisement_params
      params.require(:advertisement).permit(:description,
       :travel_date, :destiny, :type_itens, :traveler_id,
       category_attributes: [:id, :name_category])
   end
end

app/views/advertisements/edit.html.erb
<section class="advertisement-user">
    <div class="container">
      <div class="row">
          <div class="col-md-4 col-md-offset-4">
            <h1>Edição de Anúncio</h1>
          </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
        <div class='advertisement-new'>
          <%= form_for @advertisement do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <div class="field">
                <%= f.label :description, 'Descrição' %><br>
                <%= f.text_field :description %>
            <div/>

            <div class="field">
                <%= f.label :travel_date, 'Data da Viagem' %><br>
                <%= f.date_field :travel_date%>
            <div/>

            <div>
                <%= f.label :type_itens , 'Tipos de produto que pretende trazer' %>
                <%= f.select :type_itens, options_for_select([["Eletrônicos", "Eletrônicos"], ["
                    Cosméticos", "Cosméticos"], ["Brinquedos", "Brinquedos"], ["Roupas", "Roupas"], ["
                    Remédios", "Remédios"], ["Suplementos", "Suplementos"]])
                %></br></br>
            </div>

            <div class="field">
                <%= f.label :destiny, 'Destino' %><br>
                <%= f.text_field :destiny%>
            <div/>

            <center><%= f.submit class: 'btn btn-primary' %></center>
          <% end %>

        </div>
            </div>
        </div>
    </div>
</section>

app/views/advertisements/index.html.erb
<%= form_tag(ad_index_path, :method => :post) do %>
    <%= text_field_tag 'search', nil, placeholder: 'Enter search term....' %>
    <%= submit_tag "search" %>
<% end -%>

app/views/advertisements/list.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
    <div class="row">

        <% if @advertisements != nil%>

        <!-- Page header -->
        <div class="page-header">
            <h2>Anúncios disponíveis</h2>
        </div>
        <!-- /Page header -->

        <% @advertisements.each do |advertisement| %>

        <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="panel panel-primary text-center">
                <div class="panel-body">
                    <img class="img-responsive img-effect" src="http://lorempixel.com/700/500/city/<%= advertisement.id %>">
                    <h3 class="city_name">
                        <%= link_to advertisement.destiny, advertisement %>
                    </h3>
                </div>
                <div class="panel-footer">
                    <p>
                        <%= advertisement.description %>
                    </p>
                    <p>
                        <span style="font-weight: bold;">Data: </span><%= advertisement.travel_date %>
                    </p>
                </div>
            </div>
        </div>

        <% end %>
    </div>
</div>

<% else %>
<p>No momento não temos anúncios cadastrados! Em breve haverá novos anúncios :)</p>
<% end %>

app/views/advertisements/new.html.erb
<section class="new_advertisement">
    <div class="container">
      <div class="row">
          <div class="col-md-4 col-md-offset-4">
            <h1>Criação de Anúncio</h1>
          </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
        <div class='advertisement-new'>
          <%= form_for @advertisement do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <div class="field">
                <%= f.label :description, 'Descrição' %><br>
                <%= f.text_field :description %>
            <div/>

            <div class="field">
                <%= f.label :travel_date, 'Data da Viagem' %><br>
                <%= f.date_field :travel_date %>
            <div/>

            <div>
                <%= f.label :type_itens , 'Tipos de produto que pretende trazer' %>
                <%= f.select :type_itens, options_for_select([["Eletrônicos", "Eletrônicos"], ["
                    Cosméticos", "Cosméticos"], ["Brinquedos", "Brinquedos"], ["Roupas", "Roupas"], ["
                    Remédios", "Remédios"], ["Suplementos", "Suplementos"]])
                %></br></br>
            </div>


            <div class="field">
                <%= f.label :destiny, 'Destino' %><br>
                <%= f.text_field :destiny%>
            <div/>

            <div class="actions">
              <center><%= f.submit "Criar Anúncio" , class: 'btn btn-primary' %></center>
            </div>

            <p> </p>

          <% end %>

        </div>
            </div>
        </div>
    </div>
</section>

app/views/advertisements/show.html.erb
<section class="new-user">
    <div class="container">
        <div class="row">
          <div class="col-md-3">
            <div class="profile-sidebar">
              <!-- SIDEBAR USERPIC -->
              <div class="profile-userpic">
                <img class="img-responsive img-effect" src="http://lorempixel.com/200/200/people">
              </div>
              <!-- END SIDEBAR USERPIC -->
              <!-- SIDEBAR USER TITLE -->
              <div class="profile-usertitle">
                <div class="profile-usertitle-name">
                  <%= @advertisement.traveler.user_name %>
                </div>
                <div class="profile-usertitle-job">
                  Avaliação:
                  <% if @advertisement.traveler.qualification %>
                      <%= @advertisement.traveler.qualification %>
                  <% else %>
                      <p>avalie</p>
                  <% end %>
                  <br />
                  <br />

              <% if logged_in? %>
                <% if current_user.id != @advertisement.traveler_id %>
                  <%= form_tag("/advertisements/#{@advertisement.id}", method: "get", remote: false) do %>

                  <div class="btn-group" >
                    <label class="btn btn-primary">1
                    <%= radio_button_tag 'qualification', '1' %>
                    </label>
                    <label class="btn btn-primary">2
                    <%= radio_button_tag 'qualification', '2' %>
                    </label>
                    <label class="btn btn-primary">3
                    <%= radio_button_tag 'qualification', '3' %>
                    </label>
                    <label class="btn btn-primary">4
                    <%= radio_button_tag 'qualification', '4' %>
                    </label>
                    <label class="btn btn-primary">5
                    <%= radio_button_tag 'qualification', '5' %>
                    </label>

                    <%= submit_tag "Avaliar", class: "btn btn-sm btn-default" %>
                    
                    <% rate(params[:qualification], @advertisement.traveler.id) %>
                  </div>

                  <% end %>
                <% end %>
              <% end %>

               </div>
              </div>
              <!-- END SIDEBAR USER TITLE -->
              <!-- SIDEBAR BUTTONS -->
              <div class="profile-userbuttons">

              <% if logged_in? %>
                <% if current_user.id != @advertisement.traveler_id %>
                <%= link_to 'Mensagem', new_message_path(:receiver_id => @advertisement.traveler_id, :advertisement_id => @advertisement.id) , class: 'btn btn-danger btn-sm' %>
                <% end %>
              <% end %>
              </div>
              <!-- END SIDEBAR BUTTONS -->

              <!-- SIDEBAR MENU -->
              <!-- 
              <div class="profile-usermenu">
                <ul class="nav">
                  <li class="active">
                    <a href="#">
                    <i class="glyphicon glyphicon-home"></i>
                    Overview </a>
                  </li>
                  <li>
                    <a href="#">
                    <i class="glyphicon glyphicon-user"></i>
                    Account Settings </a>
                  </li>
                  <li>
                    <a href="#" target="_blank">
                    <i class="glyphicon glyphicon-ok"></i>
                    Tasks </a>
                  </li>
                  <li>
                    <a href="#">
                    <i class="glyphicon glyphicon-flag"></i>
                    Help </a>
                  </li>
                </ul>
              </div>
              -->
              <!-- END MENU -->
            </div>
          </div>

          <div class="col-md-9 bg-white">
            <div class='users-new'>
              <div class="section-title">
                <% if logged_in? %>
                  <% if current_user.id == @advertisement.traveler_id %>
                  <p>
                    <i class="glyphicon glyphicon-pencil" aria-hidden="true"></i>
                    <%= link_to 'Editar', edit_advertisement_path(id: @advertisement.id), class: '' %>
                  </p>
                  <% else %>
                  <% end %>
                <% end %>
                <img class="img-responsive img-effect" src="http://lorempixel.com/1024/200/city">
                <h1 class="city-title"><%= @advertisement.destiny %></h1>  
                <p>
                  <b>Descrição:  </b><%= @advertisement.description %>
                </p>  
                <p>
                  <b>Data da viagem:  </b><%= @advertisement.travel_date %>
                </p>  
                <p>
                  <b>Tipo de itens:  </b><%= @advertisement.type_itens %>
                </p>
              </div>
              <% if logged_in? %>
                <% if current_user.id != @advertisement.traveler_id %>
                <div><%= link_to 'Contratar', new_message_path(:receiver_id => @advertisement.traveler_id, :advertisement_id => @advertisement.id) , class: 'btn btn-lg btn-info' %></div>
                <% end %>
              <% end %>
          </div>
        </div>
      </div>
    </div>
</section>